### ISSUE TITLE
Android CustomTabs crash on API 30 and above

### ISSUE THREAD

**Issue by AbdrahumanFikry** [nyartech/hyperpay#19]
` private fun bindCustomTabsService() {
        if (mClient != null) return
        try {
            val mConnection = object : CustomTabsServiceConnection() {
                override fun onCustomTabsServiceConnected(name: ComponentName, client: CustomTabsClient) {
                    Log.d(TAG, "onCustomTabsServiceConnected CustomTabsClient = $mClient");
                    mClient = client
                    mClient!!.warmup(0L);
                }

                override fun onServiceDisconnected(name: ComponentName?) {
                    mClient = null
                }

            }
            Log.d(TAG, "mConnection =  $mConnection");

            val ok = CustomTabsClient.bindCustomTabsService(mActivity!!, CUSTOM_TAB_PACKAGE_NAME, mConnection);

            Log.d(TAG, "bindCustomTabsService : ,ok = $ok ,CustomTabsClient = $mClient");
        } catch (e: Exception) {
            Log.e(TAG, "bindCustomTabsService = $e ");
        }
    }`

bindCustomTabsServiceis always False !!

@pr-Mais

**Comment by pr-Mais** [comment]
Without providing me with the steps you did and a minimum reproducible code I cannot guess where's your problem.
Here're some steps to do before filing an issue:
1. Make sure your server endpoints are correctly setup by following [the official docs here]([set up your server](https://wordpresshyperpay.docs.oppwa.com/tutorials/mobile-sdk/integration/server)).
2. To test your endpoints, use **Postman** with the testing environment and configurations, make sure you're receiving a correct and valid JSON response.
3. Clone this repository, then paste the configurations you received from HyperPay [here](https://github.com/nyartech/hyperpay/blob/main/example/lib/constants.dart).
4. Run the example app and do a transaction using test cards.

If you followed the above steps and the example app is crashing, let me know.

**Comment by AbdrahumanFikry** [comment]
I followed the above steps and the example app is crashing.
End points are working fine 

the problem with the native code specially the function I have attached  to the pervious comment 

@pr-Mais

**Comment by pr-Mais** [comment]
It's crashing in the example app?

**Comment by pr-Mais** [comment]
The code snippet you attached is not from this plugin.

**Comment by AbdrahumanFikry** [comment]
line 172 HyperPayPlugin.kt
 `CustomTabsClient.bindCustomTabsService(mActivity!!, CUSTOM_TAB_PACKAGE_NAME, cctConnection);`
 
@pr-Mais

**Comment by pr-Mais** [comment]
I pushed a small fix in the example app, could you please pull and try again.
Additionally, the crash I got was caused by an error with the example app package name, couldn't reproduce the case you're facing.

**Comment by AbdrahumanFikry** [comment]
Didn't fix my problem 
I debugged the problem many Times and the problem with the function I sent you earlier it always return false so the callBack isn't working and I don't Know if the payment succussed or not

**Comment by AbdrahumanFikry** [comment]
I fixed this issue 
[https://github.com/AbdrahumanFikry/hyperpayPlugin/blob/main/android/src/main/kotlin/com/nyartech/hyperpay/HyperpayPlugin.kt](url)

**Comment by pr-Mais** [comment]
Could you please answer this question: the issue happens in the example app?

**Comment by pr-Mais** [comment]
Pull and try from the original repository. You seem to have pushed many changes on your fork.

**Comment by AbdrahumanFikry** [comment]
Could you please answer this question: the issue happens in the example app?
- NO

Pull and try from the original repository. You seem to have pushed many changes on your fork.
- Please TRY the example app =>  "NOT Working AT ALL " Due to some changes on Hyperpay API and customPackageName in [HyperpayPlugin.kt](https://github.com/nyartech/hyperpay/issues/url)

**Comment by pr-Mais** [comment]
Get back to the steps I mentioned in my first comment, try running a test transaction with your configurations on the example app in this repository, not your fork, purely without changing anything else.

**Comment by salahamassi** [comment]
I have the same issue after calling 

`hyperpay.pay(card);`

the plugin throws this exception 


> W/System.err(13521): java.lang.NullPointerException
> W/System.err(13521): 	at com.nyartech.hyperpay.HyperpayPlugin.transactionCompleted(HyperpayPlugin.kt:291)
> W/System.err(13521): 	at com.oppwa.mobile.connect.service.ConnectService.transactionCompleted(ConnectService.java:2)
> W/System.err(13521): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.a(OppPaymentProvider.java:64)
> W/System.err(13521): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.lambda$Z7rpKa2phFQX0DRjHjS8RQqzthY(Unknown Source:0)
> W/System.err(13521): 	at com.oppwa.mobile.connect.provider.-$$Lambda$OppPaymentProvider$Z7rpKa2phFQX0DRjHjS8RQqzthY.run(Unknown Source:8)
> W/System.err(13521): 	at java.lang.Thread.run(Thread.java:1012)
> E/AndroidRuntime(13521): FATAL EXCEPTION: Thread-4
> E/AndroidRuntime(13521): Process: sa.example.fixit.staging, PID: 13521
> E/AndroidRuntime(13521): java.lang.IllegalStateException: null️
> E/AndroidRuntime(13521): 	at com.nyartech.hyperpay.HyperpayPlugin.transactionCompleted(HyperpayPlugin.kt:320)
> E/AndroidRuntime(13521): 	at com.oppwa.mobile.connect.service.ConnectService.transactionCompleted(ConnectService.java:2)
> E/AndroidRuntime(13521): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.a(OppPaymentProvider.java:64)
> E/AndroidRuntime(13521): 	at com.oppwa.mobile.connect.provider.OppPaymentProvider.lambda$Z7rpKa2phFQX0DRjHjS8RQqzthY(Unknown Source:0)
> E/AndroidRuntime(13521): 	at com.oppwa.mobile.connect.provider.-$$Lambda$OppPaymentProvider$Z7rpKa2phFQX0DRjHjS8RQqzthY.run(Unknown Source:8)
> E/AndroidRuntime(13521): 	at java.lang.Thread.run(Thread.java:1012)
> I/Process (13521): Sending signal. PID: 13521 SIG: 9
> Lost connection to device.
> Failed to send request: {"jsonrpc":"2.0","id":"58","method":"getMemoryUsage","params":{"isolateId":"isolates/791169051683579"}}
>

**Comment by AbdrahumanFikry** [comment]
@salahamassi I solved this Issue at [https://github.com/AbdrahumanFikry/hyperpayPlugin](url)

**Comment by pr-Mais** [comment]
Unless you provide the exact steps you followed and a minimal reproducible code, we're unable to help you. I tried running a transaction in the example app on both platforms and it was successful. 

I'll close the issue, feel free to comment if you have any helpful details.

**Comment by AbdrahumanFikry** [comment]
@pr-Mais Please use the package in a new flutter app and not the example and you well get it

**Comment by pr-Mais** [comment]
I'm using the package in an app that is running in production for a year now and I had no issues on both Android and iOS.

I cannot help you unless you tell me what exactly you did that led to this exception.

**Comment by AbdrahumanFikry** [comment]
@pr-Mais I did exactly what I found in the package documentation and led to this exception!!
#Please try it your self on a new flutter project with the newest version  of every thing and you will get it!
## @salahamassi this man had the same Issue and you don't even try what we told you, what do you need to believe us the whole flutter community !!
###

**Comment by pr-Mais** [comment]
Create a repo with a minimal code that produces this exception for you and share it here please

**Comment by AbdrahumanFikry** [comment]
@pr-Mais Please create a new flutter app and use the package and follow the package documentation and 
# YOU WELL GET IT

**Comment by pr-Mais** [comment]
What's the version of the Android HyperPay SDK you are using?

**Comment by AbdrahumanFikry** [comment]
@pr-Mais 3.10.0

**Comment by pr-Mais** [comment]
Just tried a new Flutter project and it's working as expected.

Worth noting that the plugin is tested against version 3.6.0 ([check here](https://github.com/nyartech/hyperpay/tree/main/example/android/oppwa.mobile)).
I had to make some changes in the Android files to compile with v3.10.0, will update the docs shortly.

Here're the changes I did:
1. In `settings.gradle`:
```
configurations.maybeCreate("default")
artifacts.add("default", file('oppwa.mobile-3.10.0-release.aar'))
```
2. In `app/build.gradle`: set the `compileSdkVersion` to 31

---

Looking closely at the exception you're getting, I can see `java.lang.NullPointerException`, which indicates a required value by the `pay` method is being passed as `null`. 
Have you tried printing the `checkoutID` and made sure it's not `null`?

**Comment by AbdrahumanFikry** [comment]
Dear Mais ,
Please talk to the Android Developer Who coded this file and let him fix this issue `java.lang.NullPointerException`

I already solved here [[https://github.com/AbdrahumanFikry/hyperpayPlugin/blob/main/android/src/main/kotlin/com/nyartech/hyperpay/HyperpayPlugin.kt](https://github.com/nyartech/hyperpay/issues/url)](url)

**Comment by pr-Mais** [comment]
The issue is caused by Browser 1.3.0 on Android API 30 and above. A fix will be published soon.

@AbdrahumanFikry thanks for reporting, such detail about the environment that produced the issue could have helped much earlier.
